### PR TITLE
[Backend] Signup(register)

### PR DESCRIPTION
**Pull request by burakaktan**
Changes:
- [x] Created a Django model class named "User" to store users' information. 
- [x]  Created an API endpoint accepting POST requests. Endpoint URL should be "{base_url}/user/signup". When a request to this endpoint is received, system registers a new user with email address, username and password in the request.
- [x] If any field in the request  (e.g., email address) is missing or any user with that email or username already exists 400 Http Status Code is returned.
- [x] If password is shorter than 8 characters, or password doesn't contain at least 1 upper case letter, 1 lower case letter, 1 numerical digit; 400 Http Status Code is returned. See [this part of the requirements](https://github.com/bounswe/bounswe2022group9/wiki/Requirement-Analysis#42-security) for further reference about password security rules.
- [x] Created an API endpoint returning users as a list.

### CODE REVIEW

**Comment by omersisman** [comment]
There are some issues with the code and I have some suggestions for you:

1. You should delete the "print()" lines from your code before the commit.
2. The email and password verification part creates a mass in the view function. You may move the verification code to a helper method and just call the method from your view function.
3. Instead of status 200 your endpoint should return status 201 which means "created" after successful signup.
4. No need for the response message "ok" after successful signup. It may be empty.

**Comment by omersisman** [comment]
Lastly, I am not sure you need "is_json=true" parameter in the view function. I think there will be no change in the functionality without this parameter since I tried the code without this parameter and it worked.

**Comment by burakaktan** [comment]
The review comments are totally right. I did changes on the code according these reviews.
1. Unnecessary "print" lines are deleted
2. Helper methods are created in user/validation_methods.py file to make the code more modular.
3. If success is successful, 201 status code is returned instead of 200
4. Response message in success case is empty as you requested
5. "is_json=True" part is deleted since its' unnecessary

**Comment by omersisman** [comment]
The changes are very well. I am merging the branch to master.

**Pull request merged**
